//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.12 at 01:58:22 PM BRST 
//


package br.UFSC.GRIMA.application.entities.errors;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.UFSC.GRIMA.application.entities.errors package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MTConnectError_QNAME = new QName("urn:mtconnect.org:MTConnectError:1.3", "MTConnectError");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.UFSC.GRIMA.application.entities.errors
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link ErrorsType }
     * 
     */
    public ErrorsType createErrorsType() {
        return new ErrorsType();
    }

    /**
     * Create an instance of {@link HeaderType }
     * 
     */
    public HeaderType createHeaderType() {
        return new HeaderType();
    }

    /**
     * Create an instance of {@link MTConnectErrorType }
     * 
     */
    public MTConnectErrorType createMTConnectErrorType() {
        return new MTConnectErrorType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MTConnectErrorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:mtconnect.org:MTConnectError:1.3", name = "MTConnectError")
    public JAXBElement<MTConnectErrorType> createMTConnectError(MTConnectErrorType value) {
        return new JAXBElement<MTConnectErrorType>(_MTConnectError_QNAME, MTConnectErrorType.class, null, value);
    }

}
