//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.10 at 04:30:05 PM BRST 
//


package br.UFSC.GRIMA.application.entities.streams;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InterfaceEventValuesType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="InterfaceEventValuesType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="UNAVAILABLE"/>
 *     &lt;enumeration value="NOT_READY"/>
 *     &lt;enumeration value="READY"/>
 *     &lt;enumeration value="ACTIVE"/>
 *     &lt;enumeration value="COMPLETE"/>
 *     &lt;enumeration value="FAIL"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "InterfaceEventValuesType")
@XmlEnum
public enum InterfaceEventValuesType {

    UNAVAILABLE,
    NOT_READY,
    READY,
    ACTIVE,
    COMPLETE,
    FAIL;

    public String value() {
        return name();
    }

    public static InterfaceEventValuesType fromValue(String v) {
        return valueOf(v);
    }

}
