//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.10 at 04:30:05 PM BRST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:mtconnect.org:MTConnectStreams:1.3", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package br.UFSC.GRIMA.application.entities.streams;
