//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.10 at 04:30:05 PM BRST 
//


package br.UFSC.GRIMA.application.entities.streams;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         An abstract sample
 *       
 * 
 * <p>Java class for SampleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SampleType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;urn:mtconnect.org:MTConnectStreams:1.3>ResultType">
 *       &lt;attribute name="sampleRate" type="{urn:mtconnect.org:MTConnectStreams:1.3}SampleRateType" />
 *       &lt;attribute name="statistic" type="{urn:mtconnect.org:MTConnectStreams:1.3}DataItemStatisticsType" />
 *       &lt;attribute name="duration" type="{urn:mtconnect.org:MTConnectStreams:1.3}DurationTimeType" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SampleType")
@XmlSeeAlso({
    AngularVelocityType.class,
    ViscosityType.class,
    ResistanceType.class,
    SoundPressureType.class,
    PathFeedrateType.class,
    TorqueType.class,
    FrequencyType.class,
    ConductivityType.class,
    AccelerationType.class,
    SpindleSpeedType.class,
    WattType.class,
    PressureType.class,
    TiltType.class,
    PowerFactorType.class,
    TemperatureType.class,
    VelocityType.class,
    LengthType.class,
    WattageType.class,
    LinearForceType.class,
    DisplacementType.class,
    LoadType.class,
    AmperageType.class,
    VoltageType.class,
    PathPositionType.class,
    FillLevelType.class,
    ElectricalEnergyType.class,
    AccumulatedTimeType.class,
    VoltsType.class,
    GlobalPositionType.class,
    FlowType.class,
    AngularAccelerationType.class,
    StrainType.class,
    AngleType.class,
    RotaryVelocityType.class,
    ConcentrationType.class,
    AxisFeedrateType.class,
    PositionType.class,
    AbsTimeSeriesType.class
})
public abstract class SampleType
    extends ResultType
{

    @XmlAttribute(name = "sampleRate")
    protected String sampleRate;
    @XmlAttribute(name = "statistic")
    protected String statistic;
    @XmlAttribute(name = "duration")
    protected Float duration;

    /**
     * Gets the value of the sampleRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSampleRate() {
        return sampleRate;
    }

    /**
     * Sets the value of the sampleRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSampleRate(String value) {
        this.sampleRate = value;
    }

    /**
     * Gets the value of the statistic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatistic() {
        return statistic;
    }

    /**
     * Sets the value of the statistic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatistic(String value) {
        this.statistic = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setDuration(Float value) {
        this.duration = value;
    }

}
