//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.12 at 02:22:42 PM BRST 
//


package br.UFSC.GRIMA.application.entities.assets;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 *         An edge into a tool assembly
 *       
 * 
 * <p>Java class for CuttingItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CuttingItemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Description" type="{urn:mtconnect.org:MTConnectAssets:1.3}AssetDescriptionType" minOccurs="0"/>
 *         &lt;element name="Locus" type="{urn:mtconnect.org:MTConnectAssets:1.3}LocusType" minOccurs="0"/>
 *         &lt;element name="ItemLife" type="{urn:mtconnect.org:MTConnectAssets:1.3}LifeType" maxOccurs="3" minOccurs="0"/>
 *         &lt;element name="Measurements" type="{urn:mtconnect.org:MTConnectAssets:1.3}CuttingItemMeasurementsType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="indices" use="required" type="{urn:mtconnect.org:MTConnectAssets:1.3}IndexRangeType" />
 *       &lt;attribute name="itemId" type="{urn:mtconnect.org:MTConnectAssets:1.3}ItemIdType" />
 *       &lt;attribute name="grade" type="{urn:mtconnect.org:MTConnectAssets:1.3}GradeType" />
 *       &lt;attribute name="manufacturers" type="{urn:mtconnect.org:MTConnectAssets:1.3}ManufacturersType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CuttingItemType", propOrder = {
    "description",
    "locus",
    "itemLife",
    "measurements"
})
public class CuttingItemType {

    @XmlElement(name = "Description")
    protected AssetDescriptionType description;
    @XmlElement(name = "Locus")
    protected String locus;
    @XmlElement(name = "ItemLife")
    protected List<LifeType> itemLife;
    @XmlElement(name = "Measurements")
    protected CuttingItemMeasurementsType measurements;
    @XmlAttribute(name = "indices", required = true)
    protected String indices;
    @XmlAttribute(name = "itemId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String itemId;
    @XmlAttribute(name = "grade")
    protected String grade;
    @XmlAttribute(name = "manufacturers")
    protected String manufacturers;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link AssetDescriptionType }
     *     
     */
    public AssetDescriptionType getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssetDescriptionType }
     *     
     */
    public void setDescription(AssetDescriptionType value) {
        this.description = value;
    }

    /**
     * Gets the value of the locus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocus() {
        return locus;
    }

    /**
     * Sets the value of the locus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocus(String value) {
        this.locus = value;
    }

    /**
     * Gets the value of the itemLife property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemLife property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemLife().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LifeType }
     * 
     * 
     */
    public List<LifeType> getItemLife() {
        if (itemLife == null) {
            itemLife = new ArrayList<LifeType>();
        }
        return this.itemLife;
    }

    /**
     * Gets the value of the measurements property.
     * 
     * @return
     *     possible object is
     *     {@link CuttingItemMeasurementsType }
     *     
     */
    public CuttingItemMeasurementsType getMeasurements() {
        return measurements;
    }

    /**
     * Sets the value of the measurements property.
     * 
     * @param value
     *     allowed object is
     *     {@link CuttingItemMeasurementsType }
     *     
     */
    public void setMeasurements(CuttingItemMeasurementsType value) {
        this.measurements = value;
    }

    /**
     * Gets the value of the indices property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndices() {
        return indices;
    }

    /**
     * Sets the value of the indices property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndices(String value) {
        this.indices = value;
    }

    /**
     * Gets the value of the itemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * Sets the value of the itemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemId(String value) {
        this.itemId = value;
    }

    /**
     * Gets the value of the grade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrade() {
        return grade;
    }

    /**
     * Sets the value of the grade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrade(String value) {
        this.grade = value;
    }

    /**
     * Gets the value of the manufacturers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManufacturers() {
        return manufacturers;
    }

    /**
     * Sets the value of the manufacturers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufacturers(String value) {
        this.manufacturers = value;
    }

}
