//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.12 at 02:22:42 PM BRST 
//


package br.UFSC.GRIMA.application.entities.assets;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CutterStatusValueType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CutterStatusValueType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NEW"/>
 *     &lt;enumeration value="AVAILABLE"/>
 *     &lt;enumeration value="UNAVAILABLE"/>
 *     &lt;enumeration value="ALLOCATED"/>
 *     &lt;enumeration value="UNALLOCATED"/>
 *     &lt;enumeration value="MEASURED"/>
 *     &lt;enumeration value="NOT_REGISTERED"/>
 *     &lt;enumeration value="RECONDITIONED"/>
 *     &lt;enumeration value="USED"/>
 *     &lt;enumeration value="EXPIRED"/>
 *     &lt;enumeration value="TAGGED_OUT"/>
 *     &lt;enumeration value="BROKEN"/>
 *     &lt;enumeration value="UNKNOWN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CutterStatusValueType")
@XmlEnum
public enum CutterStatusValueType {

    NEW,
    AVAILABLE,
    UNAVAILABLE,
    ALLOCATED,
    UNALLOCATED,
    MEASURED,
    NOT_REGISTERED,
    RECONDITIONED,
    USED,
    EXPIRED,
    TAGGED_OUT,
    BROKEN,
    UNKNOWN;

    public String value() {
        return name();
    }

    public static CutterStatusValueType fromValue(String v) {
        return valueOf(v);
    }

}
