//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.12 at 02:22:42 PM BRST 
//


package br.UFSC.GRIMA.application.entities.assets;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * 
 *         Abstract cutter life
 *       
 * 
 * <p>Java class for LifeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LifeType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;urn:mtconnect.org:MTConnectAssets:1.3>ToolLifeValueType">
 *       &lt;attribute name="type" use="required" type="{urn:mtconnect.org:MTConnectAssets:1.3}ToolLifeType" />
 *       &lt;attribute name="countDirection" use="required" type="{urn:mtconnect.org:MTConnectAssets:1.3}ToolLifeDirectionType" />
 *       &lt;attribute name="warning" type="{urn:mtconnect.org:MTConnectAssets:1.3}ToolLifeValueType" />
 *       &lt;attribute name="limit" use="required" type="{urn:mtconnect.org:MTConnectAssets:1.3}ToolLifeValueType" />
 *       &lt;attribute name="initial" use="required" type="{urn:mtconnect.org:MTConnectAssets:1.3}ToolLifeValueType" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LifeType", propOrder = {
    "value"
})
public class LifeType {

    @XmlValue
    protected float value;
    @XmlAttribute(name = "type", required = true)
    protected ToolLifeType type;
    @XmlAttribute(name = "countDirection", required = true)
    protected ToolLifeDirectionType countDirection;
    @XmlAttribute(name = "warning")
    protected Float warning;
    @XmlAttribute(name = "limit", required = true)
    protected float limit;
    @XmlAttribute(name = "initial", required = true)
    protected float initial;

    /**
     * 
     *         The life of the tool in time, wear, or parts
     *       
     * 
     */
    public float getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     */
    public void setValue(float value) {
        this.value = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link ToolLifeType }
     *     
     */
    public ToolLifeType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToolLifeType }
     *     
     */
    public void setType(ToolLifeType value) {
        this.type = value;
    }

    /**
     * Gets the value of the countDirection property.
     * 
     * @return
     *     possible object is
     *     {@link ToolLifeDirectionType }
     *     
     */
    public ToolLifeDirectionType getCountDirection() {
        return countDirection;
    }

    /**
     * Sets the value of the countDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToolLifeDirectionType }
     *     
     */
    public void setCountDirection(ToolLifeDirectionType value) {
        this.countDirection = value;
    }

    /**
     * Gets the value of the warning property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getWarning() {
        return warning;
    }

    /**
     * Sets the value of the warning property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setWarning(Float value) {
        this.warning = value;
    }

    /**
     * Gets the value of the limit property.
     * 
     */
    public float getLimit() {
        return limit;
    }

    /**
     * Sets the value of the limit property.
     * 
     */
    public void setLimit(float value) {
        this.limit = value;
    }

    /**
     * Gets the value of the initial property.
     * 
     */
    public float getInitial() {
        return initial;
    }

    /**
     * Sets the value of the initial property.
     * 
     */
    public void setInitial(float value) {
        this.initial = value;
    }

}
